import type { SqlReadinessRegistryEntry } from '@office-unify/shared-types';

const DOCS = 'docs/sql/APPLY_ORDER.md';

function entry(
  partial: Omit<SqlReadinessRegistryEntry, 'docsPath' | 'groupName'> & {
    groupName: string;
    docsPath?: string;
  },
): SqlReadinessRegistryEntry {
  return { docsPath: DOCS, ...partial };
}

/** APPLY_ORDER.md 기준 SQL readiness registry (additive, read-only 점검용). */
export const SQL_READINESS_REGISTRY: SqlReadinessRegistryEntry[] = [
  // §1 코어
  entry({
    order: 1,
    sqlFile: 'append_web_persona_chat_phase1.sql',
    groupName: '코어 앱·포트폴리오·채팅 기반',
    label: '페르소나 채팅 세션·메시지',
    purpose: '페르소나 채팅 기본 테이블',
    requiredLevel: 'core',
    featureArea: 'persona_chat',
    expectedTables: ['web_persona_chat_sessions', 'web_persona_chat_messages'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['초기 채팅·세션 관련 기능 제한'],
    actionHint: 'docs/sql/APPLY_ORDER.md §1의 1번 SQL을 Supabase SQL Editor에 적용하세요.',
    checkSqlPreview: `select table_name from information_schema.tables
 where table_schema = 'public' and table_name in ('web_persona_chat_sessions','web_persona_chat_messages');`,
  }),
  entry({
    order: 2,
    sqlFile: 'append_web_persona_chat_requests.sql',
    groupName: '코어 앱·포트폴리오·채팅 기반',
    label: '페르소나 채팅 요청 로그',
    purpose: '요청 로그·멱등 키',
    requiredLevel: 'core',
    featureArea: 'persona_chat',
    expectedTables: ['web_persona_chat_requests'],
    expectedColumns: [{ table: 'web_persona_chat_requests', columns: ['idempotency_key'] }],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['디버깅·추적·멱등 처리 제한'],
    actionHint: 'docs/sql/APPLY_ORDER.md §1의 2번 SQL을 적용하세요.',
  }),
  entry({
    order: 3,
    sqlFile: 'append_web_persona_chat_idempotency_optional.sql',
    groupName: '코어 앱·포트폴리오·채팅 기반',
    label: '멱등 키(선택, requests에 통합)',
    purpose: '중복 요청 방지(실제 스키마는 requests SQL)',
    requiredLevel: 'optional',
    featureArea: 'persona_chat',
    expectedTables: ['web_persona_chat_requests'],
    expectedColumns: [{ table: 'web_persona_chat_requests', columns: ['idempotency_key'] }],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['중복 생성 가능성'],
    actionHint: '선택 항목입니다. 미적용 시에도 requests 테이블(2번) 적용을 우선 확인하세요.',
    checkDescription: 'deprecated 파일 — append_web_persona_chat_requests.sql 의 idempotency_key 컬럼으로 대체',
  }),
  entry({
    order: 4,
    sqlFile: 'append_web_persona_memory_optional.sql',
    groupName: '코어 앱·포트폴리오·채팅 기반',
    label: '페르소나 메모리(선택)',
    purpose: '확장 메모 기능',
    requiredLevel: 'optional',
    featureArea: 'persona_chat',
    expectedTables: ['web_persona_memory'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['확장 메모 기능 없음'],
    actionHint: '메모리 기능을 쓰지 않으면 미적용이어도 됩니다.',
  }),
  entry({
    order: 5,
    sqlFile: 'append_web_portfolio_ledger.sql',
    groupName: '코어 앱·포트폴리오·채팅 기반',
    label: '포트폴리오 원장·관심',
    purpose: '보유·관심종목 기본 테이블',
    requiredLevel: 'core',
    featureArea: 'portfolio',
    expectedTables: ['web_portfolio_holdings', 'web_portfolio_watchlist'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['GET /api/portfolio/holdings → portfolio_holdings_table_missing 등'],
    actionHint: 'docs/sql/APPLY_ORDER.md §1의 5번 SQL을 적용하세요.',
  }),
  entry({
    order: 6,
    sqlFile: 'append_web_portfolio_trade_events.sql',
    groupName: '코어 앱·포트폴리오·채팅 기반',
    label: '매매 이벤트',
    purpose: '거래 원장 이벤트',
    requiredLevel: 'core',
    featureArea: 'portfolio',
    expectedTables: ['web_portfolio_trade_events'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['거래 원장 플로우 제한'],
    actionHint: 'docs/sql/APPLY_ORDER.md §1의 6번 SQL을 적용하세요.',
  }),
  entry({
    order: 7,
    sqlFile: 'append_web_portfolio_quote_overrides.sql',
    groupName: '코어 앱·포트폴리오·채팅 기반',
    label: '보유 시세 오버라이드',
    purpose: 'google_ticker / quote_symbol 컬럼',
    requiredLevel: 'optional',
    featureArea: 'portfolio',
    expectedTables: ['web_portfolio_holdings'],
    expectedColumns: [
      { table: 'web_portfolio_holdings', columns: ['google_ticker', 'quote_symbol'] },
    ],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['시세 보정 옵션 없음'],
    actionHint: '시세 override가 필요할 때만 적용하세요.',
  }),
  entry({
    order: 8,
    sqlFile: 'append_web_portfolio_watchlist_quote_overrides.sql',
    groupName: '코어 앱·포트폴리오·채팅 기반',
    label: '관심 시세 오버라이드',
    purpose: '관심종목 ticker override 컬럼',
    requiredLevel: 'optional',
    featureArea: 'portfolio',
    expectedTables: ['web_portfolio_watchlist'],
    expectedColumns: [
      { table: 'web_portfolio_watchlist', columns: ['google_ticker', 'quote_symbol'] },
    ],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['관심종목 시세 보정 옵션 없음'],
    actionHint: '관심종목 시세 override가 필요할 때만 적용하세요.',
  }),
  // §2
  entry({
    order: 9,
    sqlFile: 'append_investor_profile.sql',
    groupName: '투자자 프로필·적합성',
    label: '투자자 프로필',
    purpose: 'web_investor_profiles',
    requiredLevel: 'recommended',
    featureArea: 'investor_profile',
    expectedTables: ['web_investor_profiles'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: [
      'GET /api/investor-profile → investor_profile_table_missing',
      'Today Brief suitability skipped',
    ],
    actionHint: 'docs/sql/APPLY_ORDER.md §2의 9번 SQL을 적용하세요.',
    checkSqlPreview: `select count(*) from information_schema.tables
 where table_schema = 'public' and table_name = 'web_investor_profiles';`,
  }),
  // §3
  entry({
    order: 10,
    sqlFile: 'append_research_followup_items.sql',
    groupName: 'Research follow-up',
    label: 'Research follow-up',
    purpose: 'web_research_followup_items',
    requiredLevel: 'recommended',
    featureArea: 'research_center',
    expectedTables: ['web_research_followup_items'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['research_followup_table_missing · 저장/PB 연계 불가'],
    actionHint: 'docs/sql/APPLY_ORDER.md §3의 10번 SQL을 적용하세요.',
  }),
  entry({
    order: 11,
    sqlFile: 'append_research_followup_items_dedupe_index.sql',
    groupName: 'Research follow-up',
    label: 'Follow-up 중복 방지 인덱스',
    purpose: '표현식 UNIQUE 인덱스',
    requiredLevel: 'recommended',
    featureArea: 'research_center',
    expectedTables: ['web_research_followup_items'],
    expectedColumns: [],
    expectedIndexes: ['web_research_followup_items_user_req_title_sym_uidx'],
    expectedRoutines: [],
    degradedSymptoms: ['중복 follow-up 방지 실패'],
    actionHint:
      '중복 행 사전 점검 후 docs/sql/APPLY_ORDER.md §3의 11번 SQL을 적용하세요. 인덱스는 SQL Editor에서 checkSqlPreview로 확인하세요.',
    checkSqlPreview: `select indexname from pg_indexes
 where tablename = 'web_research_followup_items'
   and indexname = 'web_research_followup_items_user_req_title_sym_uidx';`,
    checkDescription: '인덱스는 API에서 자동 확인하지 않을 수 있습니다. checkSqlPreview로 수동 확인하세요.',
  }),
  // §4
  entry({
    order: 12,
    sqlFile: 'append_decision_retrospectives.sql',
    groupName: '판단 복기',
    label: '판단 복기',
    purpose: 'web_decision_retrospectives',
    requiredLevel: 'recommended',
    featureArea: 'decision_retrospectives',
    expectedTables: ['web_decision_retrospectives'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['decision_retrospective_table_missing'],
    actionHint: 'docs/sql/APPLY_ORDER.md §4의 12번 SQL을 적용하세요.',
  }),
  // §5
  entry({
    order: 13,
    sqlFile: 'append_watchlist_sector_match.sql',
    groupName: '관심종목 섹터 매칭',
    label: '관심종목 섹터 매칭 메타',
    purpose: 'sector_match_* 컬럼',
    requiredLevel: 'recommended',
    featureArea: 'sector_radar',
    expectedTables: ['web_portfolio_watchlist'],
    expectedColumns: [
      {
        table: 'web_portfolio_watchlist',
        columns: [
          'sector_keywords',
          'sector_match_status',
          'sector_match_confidence',
          'sector_match_source',
          'sector_match_reason',
          'sector_matched_at',
          'sector_is_manual',
        ],
      },
    ],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['Sector Radar 키워드 매칭 preview/apply 부분 실패 또는 메타 저장 생략'],
    actionHint: 'docs/sql/APPLY_ORDER.md §5의 13번 SQL을 적용하세요.',
  }),
  // §6
  entry({
    order: 14,
    sqlFile: 'append_portfolio_holdings_incomplete.sql',
    groupName: '보유 incomplete',
    label: '보유 incomplete (NULL qty/avg)',
    purpose: 'qty·avg_price nullable 운영 준비',
    requiredLevel: 'recommended',
    featureArea: 'portfolio',
    expectedTables: ['web_portfolio_holdings'],
    expectedColumns: [
      { table: 'web_portfolio_holdings', columns: ['qty', 'avg_price'] },
    ],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: [
      'POST /api/portfolio/holdings incomplete 저장 시 NOT NULL 오류',
      'portfolio_holdings_incomplete_schema_not_ready',
    ],
    actionHint:
      '이미 ledger(5번)에서 NULL 허용이면 DDL 없이 통과할 수 있습니다. 오류 시 §6의 14번을 확인하세요.',
    checkDescription: 'nullable 여부는 API가 컬럼 존재만 확인합니다. NOT NULL 오류 시 SQL Editor에서 스키마를 확인하세요.',
  }),
  // §7
  entry({
    order: 15,
    sqlFile: 'append_web_ops_events.sql',
    groupName: '운영 로그/RPC',
    label: '운영 이벤트 로그',
    purpose: 'web_ops_events',
    requiredLevel: 'recommended',
    featureArea: 'ops',
    expectedTables: ['web_ops_events'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['운영 로그·timeout 진단 누락'],
    actionHint: 'docs/sql/APPLY_ORDER.md §7의 15번 SQL을 적용하세요.',
  }),
  entry({
    order: 16,
    sqlFile: 'append_web_ops_events_upsert_rpc.sql',
    groupName: '운영 로그/RPC',
    label: 'ops fingerprint upsert RPC',
    purpose: 'upsert_web_ops_event_by_fingerprint',
    requiredLevel: 'recommended',
    featureArea: 'ops',
    expectedTables: ['web_ops_events'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: ['upsert_web_ops_event_by_fingerprint'],
    degradedSymptoms: ['멱등 upsert 실패 시 로깅 폴백(앱은 동작 가능)'],
    actionHint: 'docs/sql/APPLY_ORDER.md §7의 16번 SQL을 적용하세요.',
    checkSqlPreview: `select routine_name from information_schema.routines
 where routine_schema = 'public' and routine_name = 'upsert_web_ops_event_by_fingerprint';`,
  }),
  // §8 통합 보강
  entry({
    order: 17,
    sqlFile: 'append_today_candidate_impressions.sql',
    groupName: 'Today Candidates · Sector Radar · Research · 관심 등록 후보',
    label: '후보 노출 이력',
    purpose: 'today_candidate_impressions',
    requiredLevel: 'recommended',
    featureArea: 'today_candidates',
    expectedTables: ['today_candidate_impressions'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['7일 관심종목 반복·미국 후보 absent 진단 DB 불가'],
    actionHint: 'docs/sql/APPLY_ORDER.md §8의 17번 SQL을 Supabase SQL Editor에 적용하세요.',
  }),
  entry({
    order: 18,
    sqlFile: 'append_sector_radar_snapshots.sql',
    groupName: 'Today Candidates · Sector Radar · Research · 관심 등록 후보',
    label: 'Sector Radar 스냅샷',
    purpose: 'sector_radar_runs / sector_radar_items',
    requiredLevel: 'recommended',
    featureArea: 'sector_radar',
    expectedTables: ['sector_radar_runs', 'sector_radar_items'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['스냅샷 기반 Today 연계·최근 run 조회 불가'],
    actionHint: 'docs/sql/APPLY_ORDER.md §8의 18번 SQL을 적용하세요.',
  }),
  entry({
    order: 19,
    sqlFile: 'append_research_report_history.sql',
    groupName: 'Today Candidates · Sector Radar · Research · 관심 등록 후보',
    label: '리포트 이력·diff',
    purpose: 'research_report_runs / research_report_diffs',
    requiredLevel: 'recommended',
    featureArea: 'research_center',
    expectedTables: ['research_report_runs', 'research_report_diffs'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['동일 종목 리포트 재사용·7일 diff 불가'],
    actionHint: 'docs/sql/APPLY_ORDER.md §8의 19번 SQL을 적용하세요.',
  }),
  entry({
    order: 20,
    sqlFile: 'append_watchlist_recommendation_candidates.sql',
    groupName: 'Today Candidates · Sector Radar · Research · 관심 등록 후보',
    label: '관심 등록 후보(pending)',
    purpose: 'watchlist_recommendation_candidates',
    requiredLevel: 'recommended',
    featureArea: 'watchlist_recommendations',
    expectedTables: ['watchlist_recommendation_candidates'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['승인형 관찰 후보 저장 불가'],
    actionHint: 'docs/sql/APPLY_ORDER.md §8의 20번 SQL을 적용하세요.',
    checkSqlPreview: `select table_name from information_schema.tables
 where table_schema = 'public'
   and table_name in (
     'today_candidate_impressions','sector_radar_runs','sector_radar_items',
     'research_report_runs','research_report_diffs','watchlist_recommendation_candidates'
   ) order by 1;`,
  }),
  entry({
    order: 21,
    sqlFile: 'append_today_candidate_feedback.sql',
    groupName: 'Today Candidates · Sector Radar · Research · 관심 등록 후보',
    label: 'Today Candidate 사용자 피드백',
    purpose: 'today_candidate_feedback',
    requiredLevel: 'recommended',
    featureArea: 'today_candidates',
    expectedTables: ['today_candidate_feedback'],
    expectedColumns: [
      { table: 'today_candidate_feedback', columns: ['feedback_action', 'idempotency_key', 'effective_until'] },
    ],
    expectedIndexes: ['today_candidate_feedback_idempotency_uidx'],
    expectedRoutines: [],
    degradedSymptoms: ['hide_7d·mark_reviewed·keep_observing 저장 불가', '피드백 반영 degraded'],
    actionHint: 'docs/sql/APPLY_ORDER.md §8의 21번 append_today_candidate_feedback.sql을 적용하세요.',
    checkSqlPreview: `select table_name from information_schema.tables
 where table_schema = 'public' and table_name = 'today_candidate_feedback';`,
  }),
  entry({
    order: 22,
    sqlFile: 'append_web_action_items.sql',
    groupName: 'Today Candidates · Sector Radar · Research · 관심 등록 후보',
    label: '통합 Action Item 인박스',
    purpose: 'web_action_items',
    requiredLevel: 'recommended',
    featureArea: 'action_items',
    expectedTables: ['web_action_items'],
    expectedColumns: [
      { table: 'web_action_items', columns: ['status', 'source_type', 'dedupe_title_norm', 'idempotency_key'] },
    ],
    expectedIndexes: ['web_action_items_user_source_title_uidx', 'web_action_items_idempotency_uidx'],
    expectedRoutines: [],
    degradedSymptoms: ['액션 인박스 저장·목록 불가', '출처별 「액션 인박스에 저장」 degraded'],
    actionHint: 'docs/sql/APPLY_ORDER.md §8의 22번 append_web_action_items.sql을 적용하세요.',
    checkSqlPreview: `select table_name from information_schema.tables
 where table_schema = 'public' and table_name = 'web_action_items';`,
  }),
  // §9 선택
  entry({
    order: 23,
    sqlFile: 'append_web_committee_turns.sql',
    groupName: '기타 선택 기능',
    label: '위원회 토론 턴',
    purpose: 'web_committee_turns',
    requiredLevel: 'optional',
    featureArea: 'committee',
    expectedTables: ['web_committee_turns'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['위원회 토론 저장 제한'],
    actionHint: '위원회 기능을 쓸 때만 적용하세요.',
  }),
  entry({
    order: 24,
    sqlFile: 'append_web_committee_followups.sql',
    groupName: '기타 선택 기능',
    label: '위원회 follow-up',
    purpose: 'committee_followup_items 등',
    requiredLevel: 'optional',
    featureArea: 'committee',
    expectedTables: ['committee_followup_items'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['위원회 follow-up 저장 제한'],
    actionHint: '위원회 follow-up을 쓸 때만 적용하세요.',
  }),
  entry({
    order: 25,
    sqlFile: 'append_web_trade_journal.sql',
    groupName: '기타 선택 기능',
    label: '매매 일지',
    purpose: 'trade_journal_entries 등',
    requiredLevel: 'optional',
    featureArea: 'trade_journal',
    expectedTables: ['trade_journal_entries'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['Trade Journal API table_missing'],
    actionHint: 'Trade Journal을 쓸 때 적용하세요.',
  }),
  entry({
    order: 26,
    sqlFile: 'append_web_decision_journal.sql',
    groupName: '기타 선택 기능',
    label: '결정 일지',
    purpose: 'web_decision_journal_entries',
    requiredLevel: 'optional',
    featureArea: 'decision_journal',
    expectedTables: ['web_decision_journal_entries'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['결정 일지 저장 제한'],
    actionHint: '결정 일지 기능을 쓸 때만 적용하세요.',
  }),
  entry({
    order: 27,
    sqlFile: 'append_web_realized_pnl_and_goals.sql',
    groupName: '기타 선택 기능',
    label: '실현손익·목표',
    purpose: 'financial_goals 등',
    requiredLevel: 'optional',
    featureArea: 'goals',
    expectedTables: ['financial_goals'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['실현손익·목표 API 제한'],
    actionHint: '목표/실현손익 기능을 쓸 때 적용하세요.',
  }),
  entry({
    order: 28,
    sqlFile: 'append_web_llm_usage_monthly.sql',
    groupName: '기타 선택 기능',
    label: 'LLM 월별 사용량',
    purpose: 'web_llm_usage_monthly',
    requiredLevel: 'optional',
    featureArea: 'llm_usage',
    expectedTables: ['web_llm_usage_monthly'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['월별 사용량 집계 없음'],
    actionHint: '사용량 집계가 필요할 때만 적용하세요.',
  }),
  entry({
    order: 29,
    sqlFile: 'append_web_dev_support.sql',
    groupName: '기타 선택 기능',
    label: '개발 지원 피드백',
    purpose: 'web_dev_support_feedback',
    requiredLevel: 'optional',
    featureArea: 'dev_support',
    expectedTables: ['web_dev_support_feedback'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['dev support 저장 제한'],
    actionHint: 'dev support를 쓸 때만 적용하세요.',
  }),
  entry({
    order: 30,
    sqlFile: 'append_trend_structured_memory.sql',
    groupName: '기타 선택 기능',
    label: '트렌드 구조화 메모리',
    purpose: 'trend_memory_signals_v2',
    requiredLevel: 'optional',
    featureArea: 'trend_memory',
    expectedTables: ['trend_memory_signals_v2'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['구조화 트렌드 메모리 제한'],
    actionHint: '트렌드 구조화 메모리를 쓸 때 적용하세요.',
  }),
  entry({
    order: 31,
    sqlFile: 'append_web_trend_memory_phase1.sql',
    groupName: '기타 선택 기능',
    label: '트렌드 메모리 phase1',
    purpose: 'trend_memory_topics 등',
    requiredLevel: 'optional',
    featureArea: 'trend_memory',
    expectedTables: ['trend_memory_topics'],
    expectedColumns: [],
    expectedIndexes: [],
    expectedRoutines: [],
    degradedSymptoms: ['Trend/Research 기억 루프 제한'],
    actionHint: '트렌드 메모리를 쓸 때 적용하세요.',
  }),
];

export function getSqlReadinessRegistry(): SqlReadinessRegistryEntry[] {
  return SQL_READINESS_REGISTRY;
}

export function getSqlReadinessRegistryByOrder(order: number): SqlReadinessRegistryEntry | undefined {
  return SQL_READINESS_REGISTRY.find((e) => e.order === order);
}

export const SQL_READINESS_GROUP_ORDER: string[] = [
  '코어 앱·포트폴리오·채팅 기반',
  '투자자 프로필·적합성',
  'Research follow-up',
  '판단 복기',
  '관심종목 섹터 매칭',
  '보유 incomplete',
  '운영 로그/RPC',
  'Today Candidates · Sector Radar · Research · 관심 등록 후보',
  '기타 선택 기능',
];
