import type { InvestmentPrinciple } from '@office-unify/shared-types';

export const DEFAULT_INVESTMENT_PRINCIPLES: Array<
  Omit<InvestmentPrinciple, 'id' | 'principleSetId' | 'createdAt' | 'updatedAt'>
> = [
  {
    principleType: 'buy',
    title: '레버리지 ETF 추가 매수 금지',
    ruleText: '레버리지/인버스 ETF는 신규·추가 매수를 금지한다.',
    checkMethod: 'blocking_boolean',
    ruleKey: 'buy_no_leveraged_etf',
    targetMetric: 'instrument_type',
    operator: 'in',
    thresholdUnit: 'instrument_type',
    requiresUserInput: false,
    appliesWhenJson: { instrumentTypes: ['leveraged_etf', 'inverse_etf'] },
    evaluationHint: '심볼/종목유형이 레버리지 ETF로 분류되면 not_met',
    weight: 1.5,
    isBlocking: true,
    appliesTo: 'all',
    sortOrder: 10,
  },
  {
    principleType: 'buy',
    title: '단일 섹터 25% 초과 시 신규 매수 보류',
    ruleText: '현재 보유 비중 추정에서 단일 섹터가 25%를 초과하면 신규 매수를 보류한다.',
    checkMethod: 'portfolio_exposure',
    ruleKey: 'buy_sector_weight_cap',
    targetMetric: 'sector_weight',
    operator: '>',
    thresholdValue: 25,
    thresholdUnit: 'percent',
    requiresUserInput: false,
    appliesWhenJson: { side: 'buy' },
    evaluationHint: '보유 종목 수 기반 섹터 비중 추정',
    weight: 1.2,
    isBlocking: true,
    appliesTo: 'all',
    sortOrder: 20,
  },
  {
    principleType: 'common',
    title: '손실 종목 물타기 전 thesis 재검토 필수',
    ruleText: '손실 중인 종목 추가 매수는 thesis/invalidation 조건을 명시해야 한다.',
    checkMethod: 'manual',
    ruleKey: 'buy_averaging_down_requires_thesis',
    targetMetric: 'thesis_consistency',
    operator: 'manual_required',
    requiresUserInput: true,
    appliesWhenJson: { side: 'buy' },
    evaluationHint: 'thesisSummary + invalidationCondition 입력 여부 우선 점검',
    weight: 1.3,
    isBlocking: true,
    appliesTo: 'all',
    sortOrder: 30,
  },
  {
    principleType: 'sell',
    title: '매도 전 thesis 훼손 여부 확인',
    ruleText: '매도는 thesis 훼손/리스크 재평가/밸류에이션 과열 등 근거를 명시한다.',
    checkMethod: 'manual',
    ruleKey: 'sell_requires_thesis_or_risk_trigger',
    targetMetric: 'sell_reason_quality',
    operator: 'manual_required',
    requiresUserInput: true,
    appliesWhenJson: { side: 'sell' },
    evaluationHint: 'exit_type + trade_reason + thesis_summary를 함께 확인',
    weight: 1.1,
    isBlocking: false,
    appliesTo: 'all',
    sortOrder: 40,
  },
  {
    principleType: 'sell',
    title: 'thesis_broken 매도는 무효화 조건 근거 필요',
    ruleText: 'thesis_broken 매도는 thesis 및 invalidation 근거를 반드시 포함한다.',
    checkMethod: 'threshold_numeric',
    ruleKey: 'sell_thesis_broken_requires_thesis_and_invalidation',
    targetMetric: 'invalidation_provided',
    operator: '=',
    thresholdValue: 1,
    thresholdUnit: 'boolean',
    requiresUserInput: false,
    appliesWhenJson: { side: ['sell'], exit_type: ['thesis_broken'] },
    evaluationHint: 'thesis_summary + invalidation_condition 입력 여부를 구조 평가',
    weight: 1.4,
    isBlocking: true,
    appliesTo: 'all',
    sortOrder: 41,
  },
  {
    principleType: 'sell',
    title: 'target_reached 매도는 목표 도달 근거 명시',
    ruleText: 'target_reached 매도는 목표가/목표수익 도달 근거를 trade_reason에 남긴다.',
    checkMethod: 'manual',
    ruleKey: 'sell_target_reached_requires_target_evidence',
    targetMetric: 'exit_reason',
    operator: 'in',
    thresholdUnit: 'enum',
    requiresUserInput: true,
    appliesWhenJson: { side: ['sell'], exit_type: ['target_reached'] },
    evaluationHint: 'trade_reason/expected_scenario에 target 관련 문구 확인',
    weight: 1.1,
    isBlocking: false,
    appliesTo: 'all',
    sortOrder: 42,
  },
  {
    principleType: 'sell',
    title: 'risk_reduction / event_avoidance는 리스크 근거 필요',
    ruleText: '리스크 축소 매도는 포트폴리오 노출 또는 이벤트 리스크 근거를 설명한다.',
    checkMethod: 'portfolio_exposure',
    ruleKey: 'sell_risk_reduction_requires_exposure_rationale',
    targetMetric: 'position_weight',
    operator: '>=',
    thresholdValue: 0,
    thresholdUnit: 'percent',
    requiresUserInput: false,
    appliesWhenJson: { side: ['sell'], exit_type: ['risk_reduction', 'event_avoidance'] },
    evaluationHint: '포트폴리오 노출과 trade_reason을 같이 판단',
    weight: 1.1,
    isBlocking: false,
    appliesTo: 'all',
    sortOrder: 43,
  },
  {
    principleType: 'sell',
    title: 'stop_loss는 사전 기준 일관성 점검',
    ruleText: 'stop_loss 매도는 사전 무효화/손절 기준과 정합해야 한다.',
    checkMethod: 'threshold_numeric',
    ruleKey: 'sell_stop_loss_requires_invalidation',
    targetMetric: 'invalidation_provided',
    operator: '=',
    thresholdValue: 1,
    thresholdUnit: 'boolean',
    requiresUserInput: false,
    appliesWhenJson: { side: ['sell'], exit_type: ['stop_loss'] },
    evaluationHint: 'invalidation_condition 존재 여부 및 감정 상태 확인',
    weight: 1.3,
    isBlocking: true,
    appliesTo: 'all',
    sortOrder: 44,
  },
  {
    principleType: 'sell',
    title: '손절 기준/리스크 축소 매도는 명시적 유형 필요',
    ruleText: '매도 시 stop_loss/risk_reduction/rebalancing_sell 중 하나의 exit_type을 명시한다.',
    checkMethod: 'threshold_numeric',
    ruleKey: 'sell_requires_exit_type',
    targetMetric: 'exit_type_presence',
    operator: '>=',
    thresholdValue: 1,
    thresholdUnit: 'count',
    requiresUserInput: false,
    appliesWhenJson: { side: 'sell' },
    evaluationHint: 'exit_type이 비어 있으면 not_met',
    weight: 1.2,
    isBlocking: true,
    appliesTo: 'all',
    sortOrder: 45,
  },
  {
    principleType: 'risk',
    title: '이벤트 리스크 전 비중 축소 검토',
    ruleText: '실적/규제/매크로 이벤트 전에 리스크 완충 계획을 점검한다.',
    checkMethod: 'score',
    ruleKey: 'event_risk_requires_plan',
    targetMetric: 'risk_plan_presence',
    operator: '>=',
    thresholdValue: 1,
    thresholdUnit: 'count',
    requiresUserInput: false,
    appliesWhenJson: { side: 'buy_or_sell' },
    evaluationHint: 'invalidation_condition이나 expected_scenario의 리스크 표현 확인',
    weight: 1,
    isBlocking: false,
    appliesTo: 'all',
    sortOrder: 50,
  },
];

